In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
#Reading the dataset
data=pd.read_csv("kindey stone urine analysis.csv")

In [6]:
data.head()

gravity    ph  osmo  cond  urea  calc  target
0    1.021  4.91   725  14.0   443  2.45       0
1    1.017  5.74   577  20.0   296  4.49       0
2    1.008  7.20   321  14.9   101  2.36       0
3    1.011  5.51   408  12.6   224  2.15       0
4    1.005  6.52   187   7.5    91  1.16       0

In [7]:
data.tail()

gravity    ph  osmo  cond  urea   calc  target
74    1.025  7.90   721  23.6   301   9.04       1
75    1.017  4.81   410  13.3   195   0.58       1
76    1.024  5.40   803  21.8   394   7.82       1
77    1.016  6.81   594  21.4   255  12.20       1
78    1.015  6.03   416  12.8   178   9.39       1

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79 entries, 0 to 78
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   gravity  79 non-null     float64
 1   ph       79 non-null     float64
 2   osmo     79 non-null     int64  
 3   cond     79 non-null     float64
 4   urea     79 non-null     int64  
 5   calc     79 non-null     float64
 6   target   79 non-null     int64  
dtypes: float64(4), int64(3)
memory usage: 4.4 KB


In [9]:
data.shape

(79, 7)

In [10]:
data.columns

Index(['gravity', 'ph', 'osmo', 'cond', 'urea', 'calc', 'target'], dtype='object')

In [11]:
data.describe

<bound method NDFrame.describe of     gravity    ph  osmo  cond  urea   calc  target
0     1.021  4.91   725  14.0   443   2.45       0
1     1.017  5.74   577  20.0   296   4.49       0
2     1.008  7.20   321  14.9   101   2.36       0
3     1.011  5.51   408  12.6   224   2.15       0
4     1.005  6.52   187   7.5    91   1.16       0
..      ...   ...   ...   ...   ...    ...     ...
74    1.025  7.90   721  23.6   301   9.04       1
75    1.017  4.81   410  13.3   195   0.58       1
76    1.024  5.40   803  21.8   394   7.82       1
77    1.016  6.81   594  21.4   255  12.20       1
78    1.015  6.03   416  12.8   178   9.39       1

[79 rows x 7 columns]>

In [12]:
data.isnull().sum()

gravity    0
ph         0
osmo       0
cond       0
urea       0
calc       0
target     0
dtype: int64

In [13]:
data.duplicated().sum()

0

In [14]:
data.drop_duplicates(inplace= True)

In [15]:
print(data.shape)

(79, 7)


In [16]:
X=data.iloc[:,0:6]
Y=data.iloc[:,6:7]

In [17]:
print(X)

    gravity    ph  osmo  cond  urea   calc
0     1.021  4.91   725  14.0   443   2.45
1     1.017  5.74   577  20.0   296   4.49
2     1.008  7.20   321  14.9   101   2.36
3     1.011  5.51   408  12.6   224   2.15
4     1.005  6.52   187   7.5    91   1.16
..      ...   ...   ...   ...   ...    ...
74    1.025  7.90   721  23.6   301   9.04
75    1.017  4.81   410  13.3   195   0.58
76    1.024  5.40   803  21.8   394   7.82
77    1.016  6.81   594  21.4   255  12.20
78    1.015  6.03   416  12.8   178   9.39

[79 rows x 6 columns]


In [18]:
print(Y)

    target
0        0
1        0
2        0
3        0
4        0
..     ...
74       1
75       1
76       1
77       1
78       1

[79 rows x 1 columns]


In [19]:
#Splitting the dataset
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.3, random_state=2)

In [20]:
print(X_train.shape)

(55, 6)


In [21]:
print(X_test.shape)

(24, 6)


In [22]:
print(Y_train.shape)

(55, 1)


In [23]:
print(Y_test.shape)

(24, 1)


In [24]:
from sklearn.preprocessing import StandardScaler
#Standardisation
ss = StandardScaler()
X_train=ss.fit_transform(X_train)
X_test= ss.fit_transform(X_test)

In [25]:
X_train

array([[-1.14856187e+00,  7.99011848e-01, -1.72192063e+00,
        -1.61377576e+00, -1.50922203e+00, -1.27696390e+00],
       [-1.01444105e+00,  2.01692311e-01, -1.22287895e+00,
        -1.38477586e+00, -9.02942751e-01, -7.69262315e-01],
       [ 3.26767070e-01, -1.53855032e-01,  5.61195053e-01,
         8.24399639e-01,  4.08136186e-01,  6.81725750e-01],
       [ 3.26767070e-01, -6.94286994e-01,  7.87880955e-02,
         2.45164598e-01, -3.57291401e-01, -6.53875590e-01],
       [-1.41680349e+00,  1.18300298e+00, -1.01494492e+00,
         5.81929157e-01, -1.33491674e+00,  8.89421854e-01],
       [ 7.29129507e-01, -9.21837294e-01,  6.81796792e-01,
         2.69411647e-03,  9.31052063e-01,  9.29807208e-01],
       [ 3.26767070e-01, -1.61871009e+00,  3.57419700e-01,
        -1.04801131e+00,  1.30239812e+00, -6.19259573e-01],
       [ 8.63250319e-01, -7.36952676e-01,  1.11429958e+00,
         8.91752550e-01,  1.34029057e+00, -9.59650411e-01],
       [-2.09716179e-01,  7.27902380e-01, -3.329

In [26]:
X_test

array([[-0.01294994,  1.02955837, -0.45767552, -1.15891827,  0.1145918 ,
        -0.99647783],
       [-0.01294994,  2.56726786,  0.59534868,  0.79232167,  0.20969969,
        -0.87191811],
       [ 0.45324773, -0.72024899,  1.06803955,  1.22987245,  0.74071876,
        -0.02147582],
       [ 0.60864695, -0.60094394,  1.0399589 ,  1.49003777,  0.36821285,
         1.33150055],
       [ 0.76404618, -1.18421306,  0.85743471,  0.14190836,  1.28758914,
         2.33656872],
       [ 2.16263918, -0.33582161,  1.50328955, -0.14190836,  2.0643036 ,
        -0.0343613 ],
       [-1.25614371, -0.45512666, -0.78060294, -0.10643127, -1.20106738,
        -0.8031955 ],
       [-1.10074449,  0.38000867, -0.85080455, -0.87510155, -0.53531213,
        -0.25341462],
       [ 0.45324773, -0.03093094,  0.36602341, -0.87510155,  1.31929177,
        -0.66145511],
       [-0.94534527, -1.02513966, -0.48107606, -0.08277988, -0.74930489,
        -0.67004544],
       [ 0.29784851, -0.68048064,  0.96975729,  1.

In [27]:
Y_train

target
27       0
10       0
45       1
59       1
18       0
76       1
0        0
11       0
32       0
71       1
62       1
9        0
75       1
17       0
78       1
58       1
8        0
60       1
77       1
26       0
53       1
12       0
16       0
2        0
50       1
19       0
68       1
6        0
46       1
64       1
24       0
5        0
3        0
33       0
69       1
38       0
65       1
51       1
74       1
42       0
4        0
39       0
37       0
20       0
31       0
63       1
47       1
49       1
34       0
7        0
43       0
22       0
72       1
15       0
40       0

In [28]:
Y_test

target
25       0
30       0
29       0
48       1
73       1
56       1
41       0
52       1
23       0
14       0
21       0
36       0
57       1
13       0
66       1
54       1
44       0
1        0
28       0
67       1
61       1
55       1
35       0
70       1

In [29]:
# Before splitting
print("Shape of X-->",X.shape )
print("Shape of Y-->",Y.shape )

Shape of X--> (79, 6)
Shape of Y--> (79, 1)


In [30]:
# After splitting
print("Shape of X_train-->",X_train.shape )
print("Shape of X_test-->",X_test.shape )
print("Shape of Y_train-->",Y_train.shape )
print("Shape of Y_test-->",Y_test.shape )

Shape of X_train--> (55, 6)
Shape of X_test--> (24, 6)
Shape of Y_train--> (55, 1)
Shape of Y_test--> (24, 1)


In [31]:
from sklearn.linear_model import LogisticRegression
lrc=LogisticRegression()
lrc.fit(X_train,Y_train)

C:\Users\singh\.jupyter\anaconda\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [32]:
Y1_pred=lrc.predict(X_test)
Y1_pred

array([0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 1], dtype=int64)

In [33]:
from sklearn.metrics import confusion_matrix
cm1=confusion_matrix(Y_test,Y1_pred)
print(cm1)

[[10  3]
 [ 3  8]]


In [34]:
#Complete performance report
from sklearn.metrics import classification_report
print("Classification report of Logistic Regression Model: \n",classification_report(Y_test,Y1_pred))

Classification report of Logistic Regression Model: 
               precision    recall  f1-score   support

           0       0.77      0.77      0.77        13
           1       0.73      0.73      0.73        11

    accuracy                           0.75        24
   macro avg       0.75      0.75      0.75        24
weighted avg       0.75      0.75      0.75        24



In [35]:
#Model Creation ---SUPPORT VECTOR MACHINE --- classification (SVC)
#DEFAULT KRNEL=RBF OR GAUSSIAN
from sklearn.svm import SVC
svmc=SVC(kernel='rbf')
svmc.fit(X_train, Y_train)

C:\Users\singh\.jupyter\anaconda\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC()

In [36]:
#Prediction -- on test dataset -- X_test
Y2_pred=svmc.predict(X_test)
print(Y2_pred)

[0 0 0 1 1 1 0 0 0 0 0 0 1 0 1 1 0 1 0 0 1 0 1 0]


In [37]:
#Evaluate performance of model --- Confusion Matrix
from sklearn.metrics import confusion_matrix
cm2=confusion_matrix(Y_test,Y2_pred)
print(cm2)

[[11  2]
 [ 4  7]]


In [38]:
#Check the accuracy
from sklearn.metrics import accuracy_score
accuracy_score(Y_test,Y2_pred)*100

75.0

In [39]:
#Complete performance report
from sklearn.metrics import classification_report
print("Classification report of Support Vector Machine(rbf): \n",classification_report(Y_test,Y2_pred))

Classification report of Support Vector Machine(rbf): 
               precision    recall  f1-score   support

           0       0.73      0.85      0.79        13
           1       0.78      0.64      0.70        11

    accuracy                           0.75        24
   macro avg       0.76      0.74      0.74        24
weighted avg       0.75      0.75      0.75        24



In [40]:
#Model Creation ---SUPPORT VECTOR MACHINE --- classification (SVC)
#KERNEL=POLYNOMIAL
from sklearn.svm import SVC
svmc2=SVC(kernel='poly')
svmc2.fit(X_train, Y_train)

C:\Users\singh\.jupyter\anaconda\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(kernel='poly')

In [41]:
#Prediction -- on test dataset -- X_test
Y2a_pred=svmc2.predict(X_test)
print(Y2a_pred)

[0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1]


In [42]:
#Evaluate performance of model --- Confusion Matrix
from sklearn.metrics import confusion_matrix
cm2a=confusion_matrix(Y_test,Y2a_pred)
print(cm2a)

[[13  0]
 [ 7  4]]


In [43]:
#Check the accuracy
from sklearn.metrics import accuracy_score
accuracy_score(Y_test,Y2a_pred)*100

70.83333333333334

In [44]:
#Complete performance report
from sklearn.metrics import classification_report
print("Classification report of Support Vector Machine(POLYNOMIAL): \n",classification_report(Y_test,Y2_pred))

Classification report of Support Vector Machine(POLYNOMIAL): 
               precision    recall  f1-score   support

           0       0.73      0.85      0.79        13
           1       0.78      0.64      0.70        11

    accuracy                           0.75        24
   macro avg       0.76      0.74      0.74        24
weighted avg       0.75      0.75      0.75        24



In [45]:
#Model Creation ---SUPPORT VECTOR MACHINE --- classification (SVC)
#KERNEL=SIGMOIDAL
from sklearn.svm import SVC
svmc3=SVC(kernel='sigmoid')
svmc3.fit(X_train, Y_train)

C:\Users\singh\.jupyter\anaconda\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(kernel='sigmoid')

In [46]:
#Prediction -- on test dataset -- X_test
Y2b_pred=svmc3.predict(X_test)
print(Y2b_pred)

[0 0 0 1 1 0 0 0 0 0 0 0 1 0 1 1 1 1 0 0 1 0 1 0]


In [47]:
#Evaluate performance of model --- Confusion Matrix
from sklearn.metrics import confusion_matrix
cm2b=confusion_matrix(Y_test,Y2b_pred)
print(cm2b)

[[10  3]
 [ 5  6]]


In [48]:
#Complete performance report
from sklearn.metrics import classification_report
print("Classification report of Support Vector Machine(sigmoid): \n",classification_report(Y_test,Y2b_pred))

Classification report of Support Vector Machine(sigmoid): 
               precision    recall  f1-score   support

           0       0.67      0.77      0.71        13
           1       0.67      0.55      0.60        11

    accuracy                           0.67        24
   macro avg       0.67      0.66      0.66        24
weighted avg       0.67      0.67      0.66        24



In [49]:
#Model Creation ---SUPPORT VECTOR MACHINE --- classification (SVC)
#KERNEL=LINEAR
from sklearn.svm import SVC
svmc1=SVC(kernel='linear')
svmc1.fit(X_train, Y_train)

C:\Users\singh\.jupyter\anaconda\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(kernel='linear')

In [50]:
#Prediction -- on test dataset -- X_test
Y2c_pred=svmc1.predict(X_test)
print(Y2c_pred)

[0 0 0 1 1 1 0 0 0 0 0 0 1 0 1 1 0 0 0 0 1 0 1 1]


In [51]:
#Evaluate performance of model --- Confusion Matrix
from sklearn.metrics import confusion_matrix
cm2c=confusion_matrix(Y_test,Y2c_pred)
print(cm2c)

[[12  1]
 [ 3  8]]


In [52]:
#Complete performance report
from sklearn.metrics import classification_report
print("Classification report of Support Vector Machine(Linear): \n",classification_report(Y_test,Y2c_pred))

Classification report of Support Vector Machine(Linear): 
               precision    recall  f1-score   support

           0       0.80      0.92      0.86        13
           1       0.89      0.73      0.80        11

    accuracy                           0.83        24
   macro avg       0.84      0.83      0.83        24
weighted avg       0.84      0.83      0.83        24



In [53]:
#NAIVE BAYES MODEL CREATION
from sklearn.naive_bayes import GaussianNB
nbc=GaussianNB()
nbc.fit(X_train,Y_train)

C:\Users\singh\.jupyter\anaconda\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [54]:
#Model Prediction
Y3_pred=nbc.predict(X_test)
Y3_pred

array([0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0], dtype=int64)

In [55]:
#Check the performance
from sklearn.metrics import confusion_matrix
cm3=confusion_matrix(Y_test,Y3_pred)
cm3

array([[9, 4],
       [4, 7]], dtype=int64)

In [56]:
#Complete performance report
from sklearn.metrics import classification_report
print("Classification report of Naive Bayes Classification Model: \n",classification_report(Y_test,Y3_pred))

Classification report of Naive Bayes Classification Model: 
               precision    recall  f1-score   support

           0       0.69      0.69      0.69        13
           1       0.64      0.64      0.64        11

    accuracy                           0.67        24
   macro avg       0.66      0.66      0.66        24
weighted avg       0.67      0.67      0.67        24



In [57]:
#Model Creation --- Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier(criterion='entropy')
dtc.fit(X_train,Y_train)

DecisionTreeClassifier(criterion='entropy')

In [58]:
Y4_pred=dtc.predict(X_test)
Y4_pred

array([1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 0], dtype=int64)

In [59]:
#Evaluate performance of model --- Confusion Matrix
from sklearn.metrics import confusion_matrix
cm4=confusion_matrix(Y_test,Y4_pred)
cm4

array([[8, 5],
       [5, 6]], dtype=int64)

In [60]:
#accuracy
from sklearn.metrics import accuracy_score
accuracy_score(Y_test,Y4_pred)*100

58.333333333333336

In [61]:
#Complete performance report
from sklearn.metrics import classification_report
print("Classification report of Random Forest Implementation: \n",classification_report(Y_test,Y4_pred))

Classification report of Random Forest Implementation: 
               precision    recall  f1-score   support

           0       0.62      0.62      0.62        13
           1       0.55      0.55      0.55        11

    accuracy                           0.58        24
   macro avg       0.58      0.58      0.58        24
weighted avg       0.58      0.58      0.58        24

